from __future__ import annotations

import pytest


@pytest.fixture(autouse=True)
def disable_live_llm_for_tests(monkeypatch, tmp_path):
    monkeypatch.setenv("USE_LLM", "false")
    monkeypatch.setenv("ANTHROPIC_API_KEY", "")
    monkeypatch.setenv("ANTHROPIC_AUTH_TOKEN", "")
    monkeypatch.setenv("ANTHROPIC_AUTH_TOJEN", "")
    monkeypatch.setenv("ANTHROPIC_BASE_URL", "")
    monkeypatch.setenv("ANTHROPIC_MODEL", "")
    monkeypatch.setenv("ANTHROPIC_VERIFY_SSL", "true")
    monkeypatch.setenv("ANTHROPIC_MAX_TOKENS", "")
    monkeypatch.setenv("ANTHROPIC_THINKING", "")
    monkeypatch.setenv("ANTHROPIC_EFFORT", "")
    monkeypatch.setenv("GROQ_API_KEY", "")
    monkeypatch.setenv("GEMINI_API_KEY", "")
    monkeypatch.setenv("GOOGLE_API_KEY", "")
    monkeypatch.setenv("GOOGLE_AI_STUDIO_API_KEY", "")
    monkeypatch.setenv("OPENAI_API_KEY", "")
    monkeypatch.setenv("APIFY_TOKEN", "")
    monkeypatch.setenv("APIFY_LINKEDIN_MAX_POSTS_PER_COMPANY", "5")
    monkeypatch.setenv("APIFY_LINKEDIN_CACHE_TTL_HOURS", "5")
    monkeypatch.setenv("APIFY_X_TWITTER_MAX_POSTS", "5")
    monkeypatch.setenv("APIFY_X_TWITTER_CACHE_TTL_HOURS", "5")
    monkeypatch.setenv("EXA_API_KEY", "")
    monkeypatch.setenv("EXA_RESEARCH_MAX_RESULTS", "5")
    monkeypatch.setenv("EXA_RESEARCH_CACHE_TTL_HOURS", "24")
    monkeypatch.setenv("EXA_RESEARCH_CONTENT_MAX_AGE_HOURS", "24")
    monkeypatch.setenv("EXA_PRESS_RECENCY_MONTHS", "18")
    monkeypatch.setenv("ADYNTEL_EMAIL", "")
    monkeypatch.setenv("ADYNTEL_API_KEY", "")
    monkeypatch.setenv("ADYNTEL_MAX_ADS_PER_PLATFORM", "5")
    monkeypatch.setenv("ADYNTEL_AD_CACHE_TTL_HOURS", "120")
    monkeypatch.setenv("AGENT_CACHE_DIR", str(tmp_path / "agent_cache"))
    monkeypatch.delenv("GROQ_OPENAI_BASE_URL", raising=False)
    monkeypatch.delenv("OPENAI_BASE_URL", raising=False)
